name: Android CI for PR check

on:
  pull_request:
    branches:
      - 'master'
      - 'release*'
      - 'dev'    

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Build Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Set up environment
      env:
        HOST: ${{ secrets.HOST }}
        TEST_ACCOUNT: ${{ secrets.TEST_ACCOUNT }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      shell: bash
      run: echo -e "HOST=$HOST\nACCOUNT=$TEST_ACCOUNT\nPASSWORD=$TEST_PASSWORD" > ./local.properties
      
    - name: Spotless Check
      run: bash ./gradlew spotlessCheck    
      
    - name: Build Test
      run: bash ./gradlew clean assembleStaging

    - name: App layer Unit Test
      run: bash ./gradlew app:testStagingDebugUnitTest
      
    - name: Domain layer Unit Test
      run: bash ./gradlew domain:testStagingDebugUnitTest
      
    - name: Data layer Unit Test
      run: bash ./gradlew data:testStagingDebugUnitTest
      
    - name: Common layer Unit Test
      run: bash ./gradlew common:testDebugUnitTest

    - name: Upload Reports
      uses: actions/upload-artifact@v3
      with:
        name: Test-Reports
        path: ~/**/**/build/reports
      if: always()
